import { createContext, useContext, useState, ReactNode } from "react";

type Language = "it" | "en" | "es";

const translations = {
  nav: {
    howItWorks: { it: "Come Funziona", en: "How It Works", es: "Cómo Funciona" },
    pricing: { it: "Tariffe", en: "Pricing", es: "Tarifas" },
    contacts: { it: "Contatti", en: "Contacts", es: "Contactos" },
    login: { it: "Accedi", en: "Login", es: "Acceder" },
  },
  hero: {
    title1: {
      it: "INVESTI CON L'IA NEI DIRITTI MUSICALI.",
      en: "INVEST WITH AI IN MUSIC RIGHTS.",
      es: "INVIERTE CON IA EN DERECHOS MUSICALES.",
    },
    title2: {
      it: "PREDIRE IL FUTURO CON I DATI.",
      en: "PREDICT THE FUTURE WITH DATA.",
      es: "PREDICE EL FUTURO CON DATOS.",
    },
    subtitle: {
      it: "Piattaforma intelligente per analizzare cataloghi, valutare rischi e prevedere rendimenti con i dati, non con l'istinto.",
      en: "Intelligent platform to analyze catalogs, assess risks, and predict returns with data, not instinct.",
      es: "Plataforma inteligente para analizar catálogos, evaluar riesgos y predecir rendimientos con datos, no con instinto.",
    },
    searchPlaceholder: {
      it: "Incolla Link Artista o Album Spotify...",
      en: "Paste Artist or Spotify Album Link...",
      es: "Pega el enlace de Artista o Álbum de Spotify...",
    },
    analyzeNow: { it: "ANALIZZA ORA", en: "ANALYZE NOW", es: "ANALIZAR AHORA" },
  },
  dashboard: {
    catalog: { it: "CATALOGO: QUEENS OF THE STONE AGE", en: "CATALOG: QUEENS OF THE STONE AGE", es: "CATÁLOGO: QUEENS OF THE STONE AGE" },
    projectionTitle: { it: "Proiezione Guadagni (5 Anni)", en: "Earnings Projection (5 Years)", es: "Proyección de Ganancias (5 Años)" },
    riskScore: { it: "RISK SCORE", en: "RISK SCORE", es: "PUNTUACIÓN DE RIESGO" },
    low: { it: "BASSO", en: "LOW", es: "BAJO" },
    keyInsights: { it: "KEY INSIGHTS", en: "KEY INSIGHTS", es: "DATOS CLAVE" },
    generatedByAi: { it: "Generato dall'IA:", en: "Generated by AI:", es: "Generado por IA:" },
    insight1: { it: "Listener stabili (2M mensili)", en: "Stable listeners (2M monthly)", es: "Oyentes estables (2M mensuales)" },
    insight2: { it: "Alta longevità del catalogo", en: "High catalog longevity", es: "Alta longevidad del catálogo" },
    insight3: { it: "Bassa dipendenza da TikTok", en: "Low TikTok dependency", es: "Baja dependencia de TikTok" },
    estimatedValue: { it: "VALORE STIMATO CATALOGO", en: "ESTIMATED CATALOG VALUE", es: "VALOR ESTIMADO DEL CATÁLOGO" },
    purchaseAdvice: { it: "CONSIGLIO D'ACQUISTO", en: "PURCHASE ADVICE", es: "CONSEJO DE COMPRA" },
  },
  features: {
    title1: { it: "Performance Storica", en: "Historical Performance", es: "Rendimiento Histórico" },
    desc1: {
      it: "Vedi la stabilità dello streaming nell'ultimo decennio.",
      en: "See streaming stability over the last decade.",
      es: "Observa la estabilidad del streaming en la última década.",
    },
    title2: { it: "Analisi Predittiva", en: "Predictive Analysis", es: "Análisis Predictivo" },
    desc2: {
      it: "Ottieni previsioni a 3-5 anni sui trend dei ricavi.",
      en: "Get 3-5 year forecasts on revenue trends.",
      es: "Obtén previsiones de 3-5 años sobre tendencias de ingresos.",
    },
    title3: { it: "Valutazione del Rischio", en: "Risk Assessment", es: "Evaluación de Riesgos" },
    desc3: {
      it: "Rileva cali virali o problemi di conformità legale.",
      en: "Detect viral drops or legal compliance issues.",
      es: "Detecta caídas virales o problemas de cumplimiento legal.",
    },
  },
  testimonial: {
    quote: {
      it: "\"Un'ora al giorno con questa piattaforma e ho validato un investimento in un catalogo rock. Incredibile.\"",
      en: "\"One hour a day with this platform and I validated an investment in a rock catalog. Incredible.\"",
      es: "\"Una hora al día con esta plataforma y validé una inversión en un catálogo de rock. Increíble.\"",
    },
    author: {
      it: "— M.A., Investitore Indipendente",
      en: "— M.A., Independent Investor",
      es: "— M.A., Inversor Independiente",
    },
  },
  footer: {
    description: {
      it: "Piattaforma AI per l'analisi e la valutazione dei diritti musicali.",
      en: "AI platform for music rights analysis and valuation.",
      es: "Plataforma de IA para el análisis y valoración de derechos musicales.",
    },
    product: { it: "Prodotto", en: "Product", es: "Producto" },
    features: { it: "Features", en: "Features", es: "Características" },
    howItWorks: { it: "Come Funziona", en: "How It Works", es: "Cómo Funciona" },
    pricing: { it: "Tariffe", en: "Pricing", es: "Tarifas" },
    roadmap: { it: "Roadmap", en: "Roadmap", es: "Hoja de Ruta" },
    resources: { it: "Risorse", en: "Resources", es: "Recursos" },
    blog: { it: "Blog", en: "Blog", es: "Blog" },
    guides: { it: "Guide", en: "Guides", es: "Guías" },
    community: { it: "Community", en: "Community", es: "Comunidad" },
    support: { it: "Supporto", en: "Support", es: "Soporte" },
    followUs: { it: "Seguici", en: "Follow Us", es: "Síguenos" },
    contacts: { it: "Contatti", en: "Contacts", es: "Contactos" },
    rights: { it: "Tutti i diritti riservati.", en: "All rights reserved.", es: "Todos los derechos reservados." },
    privacy: { it: "Privacy Policy", en: "Privacy Policy", es: "Política de Privacidad" },
    terms: { it: "Termini di Servizio", en: "Terms of Service", es: "Términos de Servicio" },
    cookies: { it: "Cookie Policy", en: "Cookie Policy", es: "Política de Cookies" },
  },
} as const;

type Translations = typeof translations;

interface I18nContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: Translations;
}

const I18nContext = createContext<I18nContextType | null>(null);

export const I18nProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>(() => {
    const browserLang = navigator.language?.toLowerCase();
    if (browserLang?.startsWith("it")) return "it";
    if (browserLang?.startsWith("es")) return "es";
    return "en";
  });

  return (
    <I18nContext.Provider value={{ lang, setLang, t: translations }}>
      {children}
    </I18nContext.Provider>
  );
};

export const useI18n = () => {
  const context = useContext(I18nContext);
  if (!context) throw new Error("useI18n must be used within I18nProvider");
  return context;
};
