import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "it" | "en";

const translations = {
  nav: {
    howItWorks: { it: "Come Funziona", en: "How It Works" },
    pricing: { it: "Tariffe", en: "Pricing" },
    contacts: { it: "Contatti", en: "Contacts" },
    login: { it: "Accedi", en: "Login" },
  },
  hero: {
    title1: {
      it: "INVESTI CON L'IA NEI DIRITTI MUSICALI.",
      en: "INVEST WITH AI IN MUSIC RIGHTS.",
    },
    title2: {
      it: "PREDIRE IL FUTURO CON I DATI.",
      en: "PREDICT THE FUTURE WITH DATA.",
    },
    subtitle: {
      it: "Piattaforma intelligente per analizzare cataloghi, valutare rischi e prevedere rendimenti con i dati, non con l'istinto.",
      en: "Intelligent platform to analyze catalogs, assess risks, and predict returns with data, not instinct.",
    },
    searchPlaceholder: {
      it: "Incolla Link Artista o Album Spotify...",
      en: "Paste Artist or Spotify Album Link...",
    },
    analyzeNow: { it: "ANALIZZA ORA", en: "ANALYZE NOW" },
  },
  dashboard: {
    catalog: { it: "CATALOGO: QUEENS OF THE STONE AGE", en: "CATALOG: QUEENS OF THE STONE AGE" },
    projectionTitle: { it: "Proiezione Guadagni (5 Anni)", en: "Earnings Projection (5 Years)" },
    riskScore: { it: "RISK SCORE", en: "RISK SCORE" },
    low: { it: "BASSO", en: "LOW" },
    keyInsights: { it: "KEY INSIGHTS", en: "KEY INSIGHTS" },
    generatedByAi: { it: "Generato dall'IA:", en: "Generated by AI:" },
    insight1: { it: "Listener stabili (2M mensili)", en: "Stable listeners (2M monthly)" },
    insight2: { it: "Alta longevità del catalogo", en: "High catalog longevity" },
    insight3: { it: "Bassa dipendenza da TikTok", en: "Low TikTok dependency" },
    estimatedValue: { it: "VALORE STIMATO CATALOGO", en: "ESTIMATED CATALOG VALUE" },
    purchaseAdvice: { it: "CONSIGLIO D'ACQUISTO", en: "PURCHASE ADVICE" },
  },
  features: {
    title1: { it: "Performance Storica", en: "Historical Performance" },
    desc1: {
      it: "Vedi la stabilità dello streaming nell'ultimo decennio.",
      en: "See streaming stability over the last decade.",
    },
    title2: { it: "Analisi Predittiva", en: "Predictive Analysis" },
    desc2: {
      it: "Ottieni previsioni a 3-5 anni sui trend dei ricavi.",
      en: "Get 3-5 year forecasts on revenue trends.",
    },
    title3: { it: "Valutazione del Rischio", en: "Risk Assessment" },
    desc3: {
      it: "Rileva cali virali o problemi di conformità legale.",
      en: "Detect viral drops or legal compliance issues.",
    },
  },
  testimonial: {
    quote: {
      it: "\"Un'ora al giorno con questa piattaforma e ho validato un investimento in un catalogo rock. Incredibile.\"",
      en: "\"One hour a day with this platform and I validated an investment in a rock catalog. Incredible.\"",
    },
    author: {
      it: "— M.A., Investitore Indipendente",
      en: "— M.A., Independent Investor",
    },
  },
  footer: {
    description: {
      it: "Piattaforma AI per l'analisi e la valutazione dei diritti musicali.",
      en: "AI platform for music rights analysis and valuation.",
    },
    product: { it: "Prodotto", en: "Product" },
    features: { it: "Features", en: "Features" },
    howItWorks: { it: "Come Funziona", en: "How It Works" },
    pricing: { it: "Tariffe", en: "Pricing" },
    roadmap: { it: "Roadmap", en: "Roadmap" },
    resources: { it: "Risorse", en: "Resources" },
    blog: { it: "Blog", en: "Blog" },
    guides: { it: "Guide", en: "Guides" },
    community: { it: "Community", en: "Community" },
    support: { it: "Supporto", en: "Support" },
    followUs: { it: "Seguici", en: "Follow Us" },
    contacts: { it: "Contatti", en: "Contacts" },
    rights: { it: "Tutti i diritti riservati.", en: "All rights reserved." },
    privacy: { it: "Privacy Policy", en: "Privacy Policy" },
    terms: { it: "Termini di Servizio", en: "Terms of Service" },
    cookies: { it: "Cookie Policy", en: "Cookie Policy" },
  },
} as const;

type Translations = typeof translations;

interface I18nContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: Translations;
}

const I18nContext = createContext<I18nContextType | null>(null);

export const I18nProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>(() => {
    const browserLang = navigator.language?.toLowerCase();
    return browserLang?.startsWith("it") ? "it" : "en";
  });

  return (
    <I18nContext.Provider value={{ lang, setLang, t: translations }}>
      {children}
    </I18nContext.Provider>
  );
};

export const useI18n = () => {
  const context = useContext(I18nContext);
  if (!context) throw new Error("useI18n must be used within I18nProvider");
  return context;
};
