import { createContext, useContext, useState, ReactNode } from "react";

type Language = "it" | "en" | "es" | "fr" | "de";

const translations = {
  nav: {
    howItWorks: { it: "Come Funziona", en: "How It Works", es: "Cómo Funciona", fr: "Comment ça marche", de: "So funktioniert's" },
    pricing: { it: "Tariffe", en: "Pricing", es: "Tarifas", fr: "Tarifs", de: "Preise" },
    contacts: { it: "Contatti", en: "Contacts", es: "Contactos", fr: "Contacts", de: "Kontakte" },
    login: { it: "Accedi", en: "Login", es: "Acceder", fr: "Connexion", de: "Anmelden" },
  },
  hero: {
    title1: {
      it: "ANALIZZATORE DELLE ROYALTY MUSICALI",
      en: "MUSIC ROYALTY ANALYZER",
      es: "ANALIZADOR DE REGALÍAS MUSICALES",
      fr: "ANALYSEUR DE ROYALTIES MUSICALES",
      de: "MUSIK-ROYALTY-ANALYSATOR",
    },
    title2: { it: "", en: "", es: "", fr: "", de: "" },
    subtitle: {
      it: "Piattaforma intelligente per analizzare cataloghi, valutare rischi e prevedere rendimenti con i dati, non con l'istinto.",
      en: "Intelligent platform to analyze catalogs, assess risks, and predict returns with data, not instinct.",
      es: "Plataforma inteligente para analizar catálogos, evaluar riesgos y predecir rendimientos con datos, no con instinto.",
      fr: "Plateforme intelligente pour analyser les catalogues, évaluer les risques et prédire les rendements avec les données, pas l'instinct.",
      de: "Intelligente Plattform zur Analyse von Katalogen, Risikobewertung und Renditeprognose mit Daten, nicht mit Instinkt.",
    },
    searchPlaceholder: {
      it: "Incolla Link Artista o Album Spotify...",
      en: "Paste Artist or Spotify Album Link...",
      es: "Pega el enlace de Artista o Álbum de Spotify...",
      fr: "Coller le lien Artiste ou Album Spotify...",
      de: "Künstler- oder Spotify-Album-Link einfügen...",
    },
    analyzeNow: { it: "ANALIZZA ORA", en: "ANALYZE NOW", es: "ANALIZAR AHORA", fr: "ANALYSER MAINTENANT", de: "JETZT ANALYSIEREN" },
  },
  dashboard: {
    catalog: { it: "CATALOGO: QUEENS OF THE STONE AGE", en: "CATALOG: QUEENS OF THE STONE AGE", es: "CATÁLOGO: QUEENS OF THE STONE AGE", fr: "CATALOGUE : QUEENS OF THE STONE AGE", de: "KATALOG: QUEENS OF THE STONE AGE" },
    projectionTitle: { it: "Proiezione Guadagni (5 Anni)", en: "Earnings Projection (5 Years)", es: "Proyección de Ganancias (5 Años)", fr: "Projection des Gains (5 Ans)", de: "Gewinnprognose (5 Jahre)" },
    riskScore: { it: "RISK SCORE", en: "RISK SCORE", es: "PUNTUACIÓN DE RIESGO", fr: "SCORE DE RISQUE", de: "RISIKOBEWERTUNG" },
    low: { it: "BASSO", en: "LOW", es: "BAJO", fr: "FAIBLE", de: "NIEDRIG" },
    keyInsights: { it: "KEY INSIGHTS", en: "KEY INSIGHTS", es: "DATOS CLAVE", fr: "POINTS CLÉS", de: "WICHTIGE ERKENNTNISSE" },
    generatedByAi: { it: "Generato dall'IA:", en: "Generated by AI:", es: "Generado por IA:", fr: "Généré par l'IA :", de: "Von KI generiert:" },
    insight1: { it: "Listener stabili (2M mensili)", en: "Stable listeners (2M monthly)", es: "Oyentes estables (2M mensuales)", fr: "Auditeurs stables (2M mensuels)", de: "Stabile Hörer (2M monatlich)" },
    insight2: { it: "Alta longevità del catalogo", en: "High catalog longevity", es: "Alta longevidad del catálogo", fr: "Haute longévité du catalogue", de: "Hohe Katalog-Langlebigkeit" },
    insight3: { it: "Bassa dipendenza da TikTok", en: "Low TikTok dependency", es: "Baja dependencia de TikTok", fr: "Faible dépendance à TikTok", de: "Geringe TikTok-Abhängigkeit" },
    estimatedValue: { it: "VALORE STIMATO CATALOGO", en: "ESTIMATED CATALOG VALUE", es: "VALOR ESTIMADO DEL CATÁLOGO", fr: "VALEUR ESTIMÉE DU CATALOGUE", de: "GESCHÄTZTER KATALOGWERT" },
    purchaseAdvice: { it: "ANALISI COMPLETATA", en: "ANALYSIS COMPLETE", es: "ANÁLISIS COMPLETADO", fr: "ANALYSE TERMINÉE", de: "ANALYSE ABGESCHLOSSEN" },
  },
  features: {
    title1: { it: "Performance Storica", en: "Historical Performance", es: "Rendimiento Histórico", fr: "Performance Historique", de: "Historische Performance" },
    desc1: {
      it: "Vedi la stabilità dello streaming nell'ultimo decennio.",
      en: "See streaming stability over the last decade.",
      es: "Observa la estabilidad del streaming en la última década.",
      fr: "Consultez la stabilité du streaming au cours de la dernière décennie.",
      de: "Sehen Sie die Streaming-Stabilität des letzten Jahrzehnts.",
    },
    title2: { it: "Analisi Predittiva", en: "Predictive Analysis", es: "Análisis Predictivo", fr: "Analyse Prédictive", de: "Prädiktive Analyse" },
    desc2: {
      it: "Ottieni previsioni a 3-5 anni sui trend dei ricavi.",
      en: "Get 3-5 year forecasts on revenue trends.",
      es: "Obtén previsiones de 3-5 años sobre tendencias de ingresos.",
      fr: "Obtenez des prévisions sur 3-5 ans des tendances de revenus.",
      de: "Erhalten Sie 3-5-Jahres-Prognosen zu Umsatztrends.",
    },
    title3: { it: "Valutazione del Rischio", en: "Risk Assessment", es: "Evaluación de Riesgos", fr: "Évaluation des Risques", de: "Risikobewertung" },
    desc3: {
      it: "Rileva cali virali o problemi di conformità legale.",
      en: "Detect viral drops or legal compliance issues.",
      es: "Detecta caídas virales o problemas de cumplimiento legal.",
      fr: "Détectez les baisses virales ou les problèmes de conformité légale.",
      de: "Erkennen Sie virale Einbrüche oder rechtliche Compliance-Probleme.",
    },
  },
  testimonial: {
    quote: {
      it: "\"Un'ora al giorno con questa piattaforma e ho validato un investimento in un catalogo rock. Incredibile.\"",
      en: "\"One hour a day with this platform and I validated an investment in a rock catalog. Incredible.\"",
      es: "\"Una hora al día con esta plataforma y validé una inversión en un catálogo de rock. Increíble.\"",
      fr: "\"Une heure par jour avec cette plateforme et j'ai validé un investissement dans un catalogue rock. Incroyable.\"",
      de: "\"Eine Stunde pro Tag mit dieser Plattform und ich habe eine Investition in einen Rock-Katalog validiert. Unglaublich.\"",
    },
    author: {
      it: "— M.A., Investitore Indipendente",
      en: "— M.A., Independent Investor",
      es: "— M.A., Inversor Independiente",
      fr: "— M.A., Investisseur Indépendant",
      de: "— M.A., Unabhängiger Investor",
    },
  },
  footer: {
    description: {
      it: "Piattaforma AI per l'analisi e la valutazione dei diritti musicali.",
      en: "AI platform for music rights analysis and valuation.",
      es: "Plataforma de IA para el análisis y valoración de derechos musicales.",
      fr: "Plateforme IA pour l'analyse et la valorisation des droits musicaux.",
      de: "KI-Plattform für die Analyse und Bewertung von Musikrechten.",
    },
    product: { it: "Prodotto", en: "Product", es: "Producto", fr: "Produit", de: "Produkt" },
    features: { it: "Features", en: "Features", es: "Características", fr: "Fonctionnalités", de: "Funktionen" },
    howItWorks: { it: "Come Funziona", en: "How It Works", es: "Cómo Funciona", fr: "Comment ça marche", de: "So funktioniert's" },
    pricing: { it: "Tariffe", en: "Pricing", es: "Tarifas", fr: "Tarifs", de: "Preise" },
    roadmap: { it: "Roadmap", en: "Roadmap", es: "Hoja de Ruta", fr: "Feuille de Route", de: "Roadmap" },
    resources: { it: "Risorse", en: "Resources", es: "Recursos", fr: "Ressources", de: "Ressourcen" },
    blog: { it: "Blog", en: "Blog", es: "Blog", fr: "Blog", de: "Blog" },
    guides: { it: "Guide", en: "Guides", es: "Guías", fr: "Guides", de: "Anleitungen" },
    community: { it: "Community", en: "Community", es: "Comunidad", fr: "Communauté", de: "Community" },
    support: { it: "Supporto", en: "Support", es: "Soporte", fr: "Support", de: "Support" },
    followUs: { it: "Seguici", en: "Follow Us", es: "Síguenos", fr: "Suivez-nous", de: "Folgen Sie uns" },
    contacts: { it: "Contatti", en: "Contacts", es: "Contactos", fr: "Contacts", de: "Kontakte" },
    rights: { it: "Tutti i diritti riservati.", en: "All rights reserved.", es: "Todos los derechos reservados.", fr: "Tous droits réservés.", de: "Alle Rechte vorbehalten." },
    privacy: { it: "Privacy Policy", en: "Privacy Policy", es: "Política de Privacidad", fr: "Politique de Confidentialité", de: "Datenschutzrichtlinie" },
    terms: { it: "Termini di Servizio", en: "Terms of Service", es: "Términos de Servicio", fr: "Conditions d'Utilisation", de: "Nutzungsbedingungen" },
    cookies: { it: "Cookie Policy", en: "Cookie Policy", es: "Política de Cookies", fr: "Politique de Cookies", de: "Cookie-Richtlinie" },
  },
} as const;

type Translations = typeof translations;

interface I18nContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: Translations;
}

const I18nContext = createContext<I18nContextType | null>(null);

export const I18nProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>(() => {
    const browserLang = navigator.language?.toLowerCase();
    if (browserLang?.startsWith("it")) return "it";
    if (browserLang?.startsWith("es")) return "es";
    if (browserLang?.startsWith("fr")) return "fr";
    if (browserLang?.startsWith("de")) return "de";
    return "en";
  });

  return (
    <I18nContext.Provider value={{ lang, setLang, t: translations }}>
      {children}
    </I18nContext.Provider>
  );
};

export const useI18n = () => {
  const context = useContext(I18nContext);
  if (!context) throw new Error("useI18n must be used within I18nProvider");
  return context;
};
