// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccotqnlwzsomiteedvvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjb3Rxbmx3enNvbWl0ZWVkdnZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMDg2MDMsImV4cCI6MjA3NzU4NDYwM30.l69lgKN29-8C8X_WYYIb0Gnbe80BVMsedBii_W056wA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});